### ISSUE TITLE
References reviewing

### ISSUE THREAD

**Issue by Kotzly** [Kotzly/BCI_MsC#1]
In this issue I am tracking the progress of reviewing 3 references that Romis told me about. All 3 works use the SSVEP paradigm, where visual stimulus of flickering lights or images results in components in the same frequencies appearing in the EEG signals, specially in the EEG from the visual cortex.

 - [x] [Aprendizado Profundo e Interfaces Cérebro-Computador](https://github.com/Kotzly/BCI_MsC/files/6105546/Aprendizado.Profundo.e.Interfaces.Cerebro-Computador.pdf)
 - [x] [Transfer Learning and SpecAugment applied to SSVEP Based BCI Classification](https://github.com/Kotzly/BCI_MsC/files/6105545/Transfer.Learning.and.SpecAugment.applied.to.SSVEP.Based.BCI.Classification.pdf)
 - [x] [Redes Neurais Profundas Triplet Aplicadas à Classificação de Sinais em Interfaces Cérebro-Computador](https://github.com/Kotzly/BCI_MsC/files/6105543/Redes_Neurais_Profundas_Triplet_Aplicadas_a_Classificacao_de_Sinais_em_Interfaces_Cerebro-Computador.pdf)
